// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const saveFeed = `-- name: SaveFeed :one
INSERT INTO feeds (id, user_id, name, url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, url, created_at, updated_at
`

type SaveFeedParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SaveFeed(ctx context.Context, arg SaveFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, saveFeed,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
