// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_feeds.sql

package database

import (
	"context"
	"database/sql"
)

const listFeeds = `-- name: ListFeeds :many
SELECT feeds.name, feeds.url, users.name AS added_by
FROM feeds
LEFT JOIN users ON feeds.user_id = users.id
`

type ListFeedsRow struct {
	Name    string
	Url     string
	AddedBy sql.NullString
}

func (q *Queries) ListFeeds(ctx context.Context) ([]ListFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsRow
	for rows.Next() {
		var i ListFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.AddedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
